### ISSUE TITLE
Config to render nicer tibble

### ISSUE THREAD

**Issue by ymgan** [kylieh10/gomx_sediment_macrofauna#17]
Hey @kylieh10 

As I am also learning Quarto (inspired by your work) I came across some settings that can help to render the data frame/tibble nicely.

Referring to line: https://github.com/kylieh10/gomx_sediment_macrofauna/blob/368fe5e7a62bdfda51153160524410b722f09ad9/quarto_pages/wrangling_data_page.qmd#L3

Quarto documentation: https://quarto.org/docs/computations/r.html#data-frames

I just discovered that we can actually choose `paged` or other settings to have nicer rendered tibble :D I recommend `paged` :D 

```yaml
---
title: "Document"
format: 
   html:
     df-print: paged
---
```
